function Mobj= get_COSTUM_river_location(inputConf, Mobj)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Yulong WANG\Documents\GitHub\river\data_q\river_location.csv
%    infos = {'Edogawa','Nakagawa','Arakawa','Sumidagawa','Tamagawa','Tsurumigawa','Ebigawa'};
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/09/09 21:00:34

%% Initialize variables.
filename = inputConf.river.location;
delimiter = ',';
startRow = 2;
riverNum = length(inputConf.river.infos);

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
% formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';
formatSpec = [repmat('%f',1,riverNum),'%[^\n\r]'];

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
Mobj.river.location = [dataArray{1:end-1}]';
Mobj.river.number = riverNum;
Mobj.river.name = inputConf.river.infos;

%% Add coordinate system information
UTMzone = regexpi(inputConf.utmZone,'\ ','split');
[Mobj.river.location(:,3),Mobj.river.location(:,4)] = wgs2utm(Mobj.river.location(:,2),Mobj.river.location(:,1),str2double(char(UTMzone{1}(1))),char(UTMzone{1}(2)));

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;