function plot_NCEP_rawdata(Num, XData1, YData1, CData1, MESSAGE)
%CREATEFIGURE(ZData1, YData1, XData1, CData1)
%  NUM: figure number
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata

%  Auto-generated by MATLAB on 23-May-2019 17:13:24

% Create figure
figure1 = figure(Num);
clf

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surface
% surface('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
%     'AlignVertexCenters','on',...
%     'EdgeColor','none',...
%     'CData',CData1);
pcolor(XData1, YData1, CData1);
shading flat

% Create ylabel
ylabel('Latitude (degrees)');

% Create xlabel
xlabel('Longtitude (degrees)');

% Create title
title(['Downloaded NCEP forcing : ', MESSAGE]);

box(axes1,'on');
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1.2 1 1],'PlotBoxAspectRatio',...
    [4.6875 1.90469932556152 1]);
set(gcf,'position',[Num*10,Num*10,800,600])
% Create colorbar
colorbar('peer',axes1);
% caxis([20 50])