function plot_TS_profile(Num, X1, Y1, X2, Y2, X3, Y3, X4, Y4, Name)
%CREATEFIGURE(X1, Y1, X2, Y2, Y3, X3, Y4)
%  NUM: figure number
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  X3:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 23-May-2019 15:15:21

% Create figure
figure1 = figure(Num);
clf

% Create subplot
subplot1 = subplot(2,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(X1,Y1,'Parent',subplot1,'Marker','x');

% Create ylabel
ylabel('Depth (m)');

if strcmpi(Name, 'temperature')
    item = 'Temperature (^{\circ}C)';
else
    item = 'Salinity (PSU)';
end
% Create xlabel
xlabel([item]);

% Create title
title('FVCOM');

box(subplot1,'on');
% Create subplot
subplot2 = subplot(2,2,2,'Parent',figure1);
hold(subplot2,'on');

% Create plot
plot(X2,Y2,'Parent',subplot2,'Marker','x','Color',[1 0 0]);

% Create ylabel
ylabel('Depth (m)');

% Create xlabel
xlabel([item]);

% Create title
title('HYCOM');

box(subplot2,'on');
% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X3,Y3,'Parent',subplot3,'Marker','x');

% Create ylabel
ylabel('Array index');

% Create xlabel
xlabel([item]);

% Create title
title('FVCOM');

box(subplot3,'on');
% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);
hold(subplot4,'on');

% Create plot
plot(X4,Y4,'Parent',subplot4,'Marker','x','Color',[1 0 0]);

% Create ylabel
ylabel('Array index');

% Create xlabel
xlabel([item]);

% Create title
title('HYCOM');

box(subplot4,'on');

set(gcf,'position',[Num*10,Num*10,800,600])
