function plot_NCEP_interp(Num, ZData1, YData1, XData1, CData1, Vertices1, Faces1, CData2, MESSAGE)
%CREATEFIGURE(ZData1, YData1, XData1, CData1, Vertices1, Faces1, CData2)
%  Num:
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  CDATA2:  patch cdata

%  Auto-generated by MATLAB on 24-May-2019 00:01:28

% Create figure
figure1 = figure(Num);
clf

% Create subplot
subplot1 = subplot(2,2,[1,2],'Parent',figure1);
hold(subplot1,'on');

% Create surface
surface('Parent',subplot1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'AlignVertexCenters','on',...
    'LineStyle',':',...
    'FaceColor','interp',...
    'CData',CData1);

% Create ylabel
ylabel('Latitude (degrees)');

% Create xlabel
xlabel('Longitude (degrees)');

% Create title
title([MESSAGE,' (regularly gridded)']);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[135 145]);
% Uncomment the following line to preserve the Y-limits of the axes
%ylim(subplot1,[34.65 35.75]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'DataAspectRatio',...
    [1 1 3],'PlotBoxAspectRatio',[3 1 1]);
% Create colorbar
colorbar('peer',subplot1);

% Create subplot
subplot3 = subplot(2,2,3,'Parent',figure1);
hold(subplot3,'on');

% Create surface
surface('Parent',subplot3,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'AlignVertexCenters','on',...
    'LineStyle',':',...
    'FaceColor','interp',...
    'CData',CData1);

% Create ylabel
ylabel('Latitude (degrees)');

% Create xlabel
xlabel('Longitude (degrees)');

% Create title
title([MESSAGE,' (smooth value)']);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot3,[139.1 140.4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot3,[34.65 35.75]);
box(subplot3,'on');
% Set the remaining axes properties
set(subplot3,'DataAspectRatio',...
    [1 1 1],'PlotBoxAspectRatio',[1.18181818181819 1 1.81818181818182]);
% Create colorbar
colorbar('peer',subplot3);

% Create subplot
subplot4 = subplot(2,2,4,'Parent',figure1);

% Create patch
patch('Parent',subplot4,'Vertices',Vertices1,'Faces',Faces1,...
    'FaceColor','flat',...
    'EdgeColor','none',...
    'CData',CData2);

% Create ylabel
ylabel('Latitude (degrees)');

% Create xlabel
xlabel('Longitude (degrees)');

% Create title
title([MESSAGE,' (interpolated result)']);

% Uncomment the following line to preserve the X-limits of the axes
xlim(subplot4,[139.1 140.4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(subplot4,[34.65 35.75]);
box(subplot4,'on');
% Set the remaining axes properties
set(subplot4,'CLim',[min(min(CData1)),max(max(CData1))],'DataAspectRatio',...
    [1 1 1],'PlotBoxAspectRatio',[1.18181818181819 1 1.81818181818182]);
% Create colorbar
colorbar('peer',subplot4);

set(gcf,'position',[Num*10,Num*10,800,600])

