function plot_VALUE(Num, Vertices1, Faces1, CData1, NAME_ITEM, NAME_LOCATION, Min, Max, DateString)
%CREATEFIGURE(Vertices1, Faces1, CData1, X1, Y1)
%  NUM: figure number
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 23-May-2019 15:01:43

% Create figure
figure1 = figure(Num);
clf

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create patch
patch('Parent',axes1,'Vertices',Vertices1,'Faces',Faces1,...
    'FaceColor','interp',...
    'CData',CData1);
shading flat

% Create ylabel
ylabel('Latitude (degree)');

% Create xlabel
xlabel('Longtitude (degree)');

if strcmpi(NAME_ITEM, 'temperature')
    item = '(^{\circ}C)';
elseif strcmpi(NAME_ITEM, 'salinity')
    item = '(PSU)';
elseif strcmpi(NAME_ITEM, 'DYE')
    item = '(-)';
elseif strcmpi(NAME_ITEM, 'age')   
    item = '(day)';
elseif (NAME_ITEM(1:3) == 'age')
    item = '(day)';
elseif strcmpi(NAME_ITEM, 'zeta')   
    item = '(meter)';
end

% Create title
title([DateString, ': ', 'water ',NAME_ITEM, ' of ', NAME_LOCATION, ' ', item]);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[139.1 140.4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[34.65 35.75]);
box(axes1,'on');
% Set the remaining axes properties
if strcmpi(NAME_ITEM, 'age')  
    set(axes1,'XDir','normal','CLim',[0 80]);
elseif (NAME_ITEM(1:3) == 'age')
    set(axes1,'XDir','normal','CLim',[0 80]);
else
    set(axes1,'XDir','normal','CLim',[Min Max]);
end
set(axes1,'DataAspectRatio',[1.2 1 1],'PlotBoxAspectRatio',...
    [1 1 1]);
set(gcf,'position',[Num*10,Num*10,800,600])
% Create colorbar
colorbar('peer',axes1);


