function plot1dscal(time, value, In_title, In_ylabel)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data, time
%  Y1:  vector of y data, 1d value

%  Auto-generated by MATLAB on 17-Nov-2020 22:14:06
% Example
% plot1dscal(ncfile.T(timebeg:timeend), ncfile.mettemp(station,timebeg:timeend),...
%     'Hourly Atmospheric Temperature (Chiba Station)',...
%     'Temperature ($^{o}C$)');
% saveas(gcf,'chiba_temp.png');

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
tidx = size(value,1);
for i = 1:tidx
    plot(time,value(i,:),'LineWidth',2);
    hold on;
end

% Create title
title(In_title,'Interpreter','latex');

% Create ylabel
ylabel({In_ylabel},'FontName','Times New Roman','Interpreter','latex');

% Create xlabel
xlabel({'Time'},'FontName','Times New Roman','Interpreter','latex');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.5 1.5]);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',18);
set(axes1,'XGrid','on','YGrid','on');
set(gcf,'position',[0 0 1600 400]);